// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum DatePartSelector
{
	year("1621464b-9b03-4ebe-a8b9-86b3d650417d"),
	month("e2fc1382-4df9-4877-b156-1ace804c63f5"),
	day("5205faa6-2687-4a83-907e-c150b8bdaf22");

	private final java.lang.String i18nCaptionKey;
	
	private DatePartSelector(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
