// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("1c935468-27aa-46e8-b27a-93ab768e4d51"),
	Debug("63c18e89-1b45-4975-aa6e-58b487b67c85"),
	Info("7aec706c-137b-4af3-a0ee-0058847d1009"),
	Warning("67ccff93-1541-4254-a637-a91381fecce2"),
	Error("e6d65e36-7610-4fcf-9e14-48910264db13"),
	Critical("54cfb947-1e12-4884-a59b-f56cc88c297a");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
