// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("750304db-00a1-4839-ac3e-1d072729e602"),
	FORMATTING("1116451e-c7c5-4824-8d74-74960210d3aa"),
	IMAGES("ee77b7a3-b967-4634-a77c-25af7e348e4a"),
	LINKS("48340ad2-f24a-4f2e-ac3f-f175ef632177"),
	STYLES("50b079e8-c4bb-4553-b856-b4bc97c6962c"),
	TABLES("2ed89985-a359-4562-a506-7eda0617eda1");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
