// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("063afd6d-27d5-4bc4-8445-3531cec121dc"),
	ISO_8859_1("09543831-ce41-42b9-bdb1-2e955fafa66f"),
	UTF_8("52e9d94e-f911-4a22-9c0f-3061a98b8520"),
	UTF_16BE("80913464-2e14-487d-9452-e12d70ff288b"),
	UTF_16LE("1f617159-514e-4dbd-a1e2-f630efe8a848"),
	UTF_16("f911b99d-81ff-42ad-bbb7-c725a0e68e46");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
