// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DocumentRequest_Status
{
	Pending("abb49283-f8ad-426a-a333-2e00a3756d35"),
	Completed("13fe591d-961e-44c0-8b87-f059e7292d39"),
	Failed("98c1b7e2-00b7-4ded-84d8-ab9b3c188a68");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DocumentRequest_Status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
