// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_ServiceType
{
	_Local("76988335-1505-43ed-bf57-315a85d3e84f"),
	_Cloud("98d349b6-cc0e-4a5c-8e46-e77a338e469e"),
	_Private("d7d29502-04e8-4c14-92bf-e6eede7dd145");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
