// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_RegistrationStatus
{
	Registered("2418858a-33f9-4510-a7fe-e2843cfd2b64"),
	Unregistered("d84fe7f8-acb3-43e2-800d-13f09910e9b7");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_RegistrationStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
