// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DeploymentType
{
	MendixPublicCloud("fef87f71-b225-4333-897e-297b1c436ec5"),
	MendixPrivateCloud("2777cbe8-223f-4b86-930d-ae0d0f38a915"),
	MendixCloudDedicated("7d255556-24e0-4185-923b-0b439f85130a"),
	Other("382a26f7-42c3-476c-82d3-41863524dc84");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DeploymentType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
