// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("cf788d68-88bf-4378-9187-6d9e8f66e96b"),
	Geocodio("4501b84a-230c-40a6-9500-27733f23d31b"),
	LocationIQ("e70f9c3e-07f3-4e5b-996a-b4d6ad23dab4"),
	MapQuest("de77a2bd-242b-4cbf-9355-1da4a015ae9d");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
