// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public enum HeaderFooter
{
	Both("8a1812aa-b1c1-4d2f-8108-bfaf0d203405"),
	Header("0236126d-8729-4682-8b80-a399447e274b"),
	Footer("bc299e0e-ffea-40ae-8d08-47b2074f3f6b");

	private final java.lang.String i18nCaptionKey;
	
	private HeaderFooter(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
