// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("57bf4df9-45db-461c-8180-52312d9f935d"),
	startsWith("56732752-4560-4e98-a650-eabe3e6b262b"),
	endsWith("86c1d5c1-43ef-4964-8413-776c8b8040eb"),
	between("8c7bdadf-08ab-41b4-8fd6-8dd539e5bbb0"),
	greater("2d97bc70-0f7e-4df8-9663-772d0422bb5e"),
	greaterEqual("2bb2ffcc-67af-4c86-a135-8625de378658"),
	equal("938664e3-f502-44a7-94e9-5f8143e47990"),
	notEqual("d2d88b58-ea73-4650-a6cc-9f1299e94247"),
	smaller("3fb52d18-4406-40ef-9594-9f69f2761f5d"),
	smallerEqual("e3d75406-5bee-492b-8ba9-a73307dbaebb"),
	empty("0ccd2903-4a00-4de6-95df-906fc2f17213"),
	notEmpty("3f21d355-3fef-4307-a30c-6fe4c9e4bbdf");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
